martinohmann/hcl-rs

src/de.rs, src/lib.rs, src/parser/mod.rs, src/structure/attribute.rs, src/structure/block.rs, src/structure/body.rs, src/structure/mod.rs
This allows to parse HCL into a `Body` structure which preserves
context.
=> feat: export `hcl::parse`

src/parser/grammar/hcl.pest
Heredocs are newline sensitive.  
```
heredocTemplate = (
("<<" | "<<-") Identifier Newline
(content as defined in prose above)
Identifier Newline
);
````
The `Identifier` to start the heredoc must be terminated immediately by a newline, no whitespace allowed.  To end the heredoc it must be preceded by a newline and optional whitespace.  
The current implementation fails on this valid HCL.
```
heredoc { 
data = <<EOF
// blah blah terminates at EOF
do logic
EOF
}
```
Yet accepts this invalid HCL
```
heredoc { 
data = <<EOF This is not valid EOF 
}
```
The grammar has been updated to correct that behavior.    It is also necessary to trim with `<<-` but that can be addressed later bringing up another topic integration testing.  
I'd like to propose integration testing similar to HCL's own …
=> fix(parsers): Fix heredoc handling to match HCL spec

specsuite/hcl/heredoc-double-EOF.hcl.json, specsuite/hcl/heredoc-indent.hcl.json, specsuite/hcl/heredoc.hcl, specsuite/hcl/heredoc.hcl.json, specsuite/hcl/known-issues/heredoc-nonspace-indent.hcl, specsuite/hcl/known-issues/heredoc-nonspace-indent.hcl.json, src/parser/grammar/hcl.pest, src/parser/mod.rs
In #11 support for stripping indent from herdocs was added along with
some heredoc test cases from the original specsuite.
However there were some issues with it that just surfaced now:
- As per the spec, heredocs must include a trailing newline which was
stripped until now. The parser was adjusted to preserve these by
explicitly making them part of the heredoc content.
- Some newlines in test cases got lost when adding the heredoc test
cases from the original specsuite.
- I messed up the expected test results. Now the expected output is
exactly the same as in the spec. This uncovered two issues that need
fixing: handling of leading unicode spaces and tabs.
Ignoring the failure for the tab and unicode cases for now.
=> fix: heredocs must be newline-terminated

Cargo.toml, specsuite/main.rs
When a file containing a large number of tests fails, it's impossible with the current output to easily determine what failed without copying the output to text files and running a manual diff.  
This cleans it up by indenting to better associate the message with the test, and then using a diff function to pinpoint failures.
Example of the new failure output
```
test specsuite/hcl/heredoc.hcl - specsuite/hcl/heredoc.hcl.json ... FAILED
Comment: Heredoc cases from the original specsuite at https://github.com/hashicorp/hcl/blob/65731f3310963019707cb1ee851b7c12779a4f62/specsuite/tests/expressions/heredoc.hcl
json atoms at path ".normal.basic" are not equal:
lhs:
"Foo\nBar\nBaz"
rhs:
"Foo\nBar\nBaz\n"
test specsuite/hcl/invalid-heredoc.hcl - specsuite/hcl/invalid-heredoc.hcl.json ... ok
```
=> test(specsuite): improve failure output

specsuite/hcl/operators.hcl, specsuite/hcl/operators.hcl.json, src/lib.rs, src/parser/mod.rs, src/structure/attribute.rs, src/structure/body.rs, src/structure/expression.rs, src/structure/mod.rs
Adds an `Expression` type to improve the representation of `Attribute`
value expressions.
This is similar to `Value` with the difference that it also allows to
represents expressions that are neither a primitive (e.g. bool) or a
collection (e.g. object) as a `RawExpression`. In the future the
`Expression` enum can be extended to also receive variants for other
expressions like `Conditional` or `FunctionCall`.
For `RawExpression` acts as a catchall variant for those. Its string
representation is an interpolated string (`"${expression}"`).
The `Expression` type will become useful when implementing an HCL
serializer as there is some context needed to serialize expressions
correctly.
This is a BREAKING CHANGE but will still only result in a minor version
bump since we're still pre-v1.
=> feat(structure): add `Expression` type

README.md, src/de.rs, src/error.rs, src/lib.rs, src/structure/body.rs, src/structure/de.rs, src/structure/mod.rs
This PR adds specialization for the `hcl::Body` type to the `Deserializer`. With this, it's possible to deserialize into `hcl::Body` directly to preserve context about the HCL structure. See the added example.
=> feat: specialize deserialization for `hcl::Body`

src/ser/format.rs, src/ser/tests.rs
Previously, empty blocks were rendered as:
empty {
}
With this change they are rendered as:
empty {}
=> fix(serializer): do not emit newline if block body is empty

src/error.rs, src/parser/mod.rs, src/parser/tests.rs, src/parser/unescape.rs
This initial implementation is relatively naive but it should be good enough for the start.
=> fix: unescape strings while parsing

README.md, src/lib.rs, src/macros.rs, src/structure/mod.rs, src/structure/ser.rs, src/tests.rs
Adds some macros to ease building HCL data structures and an `ExpressionSerializer` which is used inside the `expression!` macro.
=> feat: add `hcl::body!` macro and others

specsuite/hcl/invalid-heredoc.hcl.json, src/parser/grammar/hcl.pest, src/parser/mod.rs, src/parser/tests.rs
This is closer to the original HCL spec now.
=> fix(parser): correctly handle ExprTerm traversal

src/de/tests.rs, src/value/de.rs
Fixes #44
Deserialization into custom struct with `Option<T>` fields caused an
error:
```
Message { msg: "invalid type: string \"./test.spec\", expected option", location: None }
```
The previous implementation of `deserialize_option` just forwarded to `deserialize_any` which was incorrect.
=> fix: implement `deserialize_option` for `ValueDeserializer`

src/number.rs, src/parser/grammar/hcl.pest, src/parser/mod.rs, src/parser/tests.rs
The HCL spec does not specify negative numbers and represents them as
negate operations on positive integers and floats.
This change updates the parser to peek into unary operations and promote
negations on numbers to negative numbers instead. This behaviour will
most likely be kept even after adding the `Operation` variant to the
`Expression` type at one point.
=> fix: parse negate operations on numbers as negative numbers

Cargo.toml, specsuite/hcl/invalid-heredoc.hcl.json
This also allows us to reenable an ignored test.
=> chore(deps): bump pest from 2.1.3 to 2.2.1

src/format/impls.rs, src/parser/mod.rs, src/parser/tests.rs, src/ser/tests.rs, src/structure/de.rs, src/structure/expression.rs, src/structure/ser/expression.rs, src/template.rs
This adds supports for parsing and serializing variable expressions. Right now only bare identifiers like `var` are supported. Element access like `var.foo` will come later since this is a different type of expression.
=> feat: add `Expression::VariableExpr`

src/de/tests.rs, src/format/impls.rs, src/lib.rs, src/parser/mod.rs, src/parser/tests.rs, src/ser/tests.rs, src/structure/de.rs, src/structure/element_access.rs, src/structure/expression.rs, src/structure/mod.rs, src/structure/ser/element_access.rs, src/structure/ser/expression.rs, src/structure/ser/mod.rs
This adds supports for parsing and serializing element access on expression like `some_var.some_attribute` or `foo[0]`.
=> feat: add `Expression::ElementAccess`

specsuite/hcl/terraform.hcl.json, src/de/tests.rs, src/format/impls.rs, src/format/mod.rs, src/lib.rs, src/parser/grammar/hcl.pest, src/parser/mod.rs, src/parser/tests.rs, src/ser/tests.rs, src/structure/de.rs, src/structure/expression.rs, src/structure/func.rs, src/structure/mod.rs, src/structure/ser/expression.rs, src/structure/ser/func.rs, src/structure/ser/mod.rs
This adds supports for parsing and serializing function call expressions of the form `func_name(arg1, arg2...)`.
=> feat: add `Expression::FuncCall`

src/format/impls.rs, src/parser/grammar/hcl.pest, src/parser/mod.rs, src/ser/tests.rs, src/structure/de.rs, src/structure/expression.rs, src/structure/ser/expression.rs
This adds supports for parsing and serializing sub expressions (expressions wrapped in parenthesis).
=> feat: add `Expression::SubExpr`

specsuite/hcl/invalid-heredoc.hcl.json, src/format/impls.rs, src/lib.rs, src/parser/grammar/hcl.pest, src/parser/mod.rs, src/parser/tests.rs, src/ser/tests.rs, src/structure/conditional.rs, src/structure/de.rs, src/structure/expression.rs, src/structure/mod.rs, src/structure/ser/conditional.rs, src/structure/ser/expression.rs, src/structure/ser/mod.rs, src/structure/ser/tests.rs
This adds supports for parsing and serializing conditionals (e.g. `attr = var.some_cond ? true_expr : false_expr`).
=> feat: add `Expression::Conditional`

src/de/tests.rs, src/format/impls.rs, src/macros.rs, src/parser/grammar/hcl.pest, src/parser/mod.rs, src/parser/template.rs, src/ser/tests.rs, src/structure/de.rs, src/structure/expression.rs, src/structure/for_expr.rs, src/structure/mod.rs, src/structure/ser/expression.rs, src/structure/ser/for_expr.rs, src/structure/ser/mod.rs, src/structure/ser/tests.rs
This adds supports for parsing and serializing `for` expressions, e.g. `attr = [for item in items : func(item)]` and `attr = {for key, value in objects : tolower(key) => value if value != null}`.
=> feat: add `Expression::ForExpr`

Cargo.toml, src/format/impls.rs, src/macros.rs, src/ser/tests.rs, src/structure/expression.rs, src/structure/ser/expression.rs, src/structure/ser/tests.rs, src/tests.rs
BREAKING CHANGE: The underlying map implementation for the `Object<K, V>` type changed from `IndexMap<K, V>` to `VecMap<K, V>`. For the most common operations this is a drop-in replacement, but `VecMap` lacks some of the more exotic APIs the `IndexMap` provides.
This change is necessary to add support for `Expression` as object key type since it is not `Hash` and not `Ord`.
=> feat!: use `VecMap` for object expressions

src/de/tests.rs, src/format/impls.rs, src/format/mod.rs, src/macros.rs, src/number.rs, src/parser/mod.rs, src/ser/tests.rs, src/structure/attribute.rs, src/structure/block.rs, src/structure/body.rs, src/structure/conditional.rs, src/structure/de.rs, src/structure/element_access.rs, src/structure/expression.rs, src/structure/for_expr.rs, src/structure/func.rs, src/structure/mod.rs, src/structure/operation.rs, src/structure/ser/expression.rs, src/template.rs, src/tests.rs
BREAKING CHANGE: The `RawExpression` and `String` variants of the `ObjectKey`
enum were removed in favor of the newly added `Expression` variant. Furthermore
the methods `Object::raw_expression` and `ObjectKey::string` were removed. Use
`ObjectKey::from` instead.
https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md#collection-values
Object keys can either be identifiers or any valid HCL expression.
This is the last missing piece to enable the implementation of expression
evaluation.
=> feat!: allow any HCL expression as object key

src/format/impls.rs, src/format/mod.rs, src/number.rs, src/parser/mod.rs, src/structure/de.rs, src/structure/expression.rs, src/structure/ser/expression.rs, src/tests.rs, src/value/de.rs, src/value/from.rs
BREAKING CHANGE: The `Number` type was changed from an `enum` to an opaque `struct`. Use `Number::from` to create a number from an integer. Furthermore, the `From` implementations for `f32` and `f64` were removed. Use the newly added `Number::from_f64` instead.
This ensures that any number is finite and is almost identical to what `serde_json` does. Infinite floats get converted to `Value::Null` and `Expression::Null` respectively when working with the `Value` and `Expression` types.
=> fix!: prevent creation of infinite and NaN `Number`

src/de/tests.rs, src/parser/grammar/hcl.pest, src/parser/mod.rs
Fixes #83
The leading `.` was included when attempting to parse the integer index, which rightfully failed.
=> fix(parser): panic when parsing `LegacyIndex` traversal operator

benches/benchmark.rs, specsuite/hcl/invalid-heredoc.hcl.json, src/parser/grammar/hcl.pest, src/parser/mod.rs, src/parser/tests.rs
Previously, the parser needed to do a lot of backtracking while parsing conditionals and operations which massively degraded performance for deeply nested expressions.
This fix inlines the handling for operations and conditionals into the `Expression` rule so that an already matched `ExprTerm` rule does not need to be re-evaluated when no operation/conditional is matched (which is the case in the vast majority of cases since literal values and collections are way more common than these.
Fixes #82
=> fix(parser): greatly improve expression parsing performance

src/format/mod.rs, src/format/tests.rs
=> fix(format): identifiers starting with underscores are valid

src/format/mod.rs, src/structure/expression.rs, src/value/mod.rs
Add `to_string_unchecked` to the `format` module and `strict_mode` option to the `Formatter`.
This is not public API since it might be removed again in favor of the changes proposed in #93. I'm undecided about the direction to go at the moment.
For now it's here to ensures that the `to_string` implementations of `Expression` and `Value` will never ever cause a panic. Since we cannot signal an error there, it's better to at least do best effort and return the formatted result even if identifiers are not valid.
=> fix: ensure `Display` impls of `Expression` and `Value` can not fail

src/error.rs, src/parser/mod.rs, src/parser/template.rs, src/structure/mod.rs
BREAKING CHANGE: The trait bound of `Identifier::new` changed from `Into<String>` to `AsRef<str>` and the inner `String` field of `Identifier` is now private to prevent direct modification.
For most use cases this change shouldn't cause any issues. Identifiers are now automatically sanitized upon creation via `Identifier::new`. With `Identifier::from_str` a fallible alternative is provided in order to detect invalid identifiers. Furthermore `Identifier::new_unchecked` allows the creation of identifier without any validation. This can skip the sanitization if the caller already knows that the identifier is valid.
=> fix!: sanitize identifiers upon creation

src/parser/mod.rs, src/structure/attribute.rs, src/structure/de.rs, src/structure/mod.rs, src/structure/ser/attribute.rs, src/structure/ser/body.rs, src/structure/ser/structure.rs
BREAKING CHANGE: The `Attribute` struct's `key` field type was changed from `String` to `Identifier`. Furthermore, the trait bound for the attribute identifier on `Attribute::new` changed from `Into<String>` to `Into<Identifier>`.
This fixes a long standing issue. `Identifier` was introduced after `Attribute` and the field type wasn't updated yet.
=> fix!: change `Attribute` key field type to `Identifier`

src/parser/mod.rs, src/structure/block.rs, src/structure/de.rs, src/structure/mod.rs, src/structure/ser/block.rs
BREAKING CHANGE: The `Block` struct's `identifier` field type was changed from `String` to `Identifier`. Furthermore, the trait bound for the block identifier on `Block::new` changed from `Into<String>` to `Into<Identifier>`.
This fixes a long standing issue. `Identifier` was introduced after `Block` and the field type wasn't updated yet.
=> fix!: change `Block` identifier field type to `Identifier`

src/de/tests.rs, src/parser/mod.rs, src/parser/tests.rs, src/ser/tests.rs, src/structure/de.rs, src/structure/expression.rs, src/structure/ser/expression.rs, src/structure/ser/tests.rs, src/template.rs
BREAKING CHANGE: The type of `Expression`'s `Variable` variant changed from `Identifier` to `Variable`. You can create a variable from an identifier via `Variable::from(identifier)` or by using `Variable::new` and `Variable::sanitized`.
This change is necessary to better distiguish between variables and bare identifiers and to be able to clean up some trait bounds.
=> fix!: change type of `Expression::Variable` variant

src/eval/mod.rs, src/format/impls.rs, src/ident.rs, src/lib.rs, src/parser/mod.rs, src/structure/attribute.rs, src/structure/block.rs, src/structure/de.rs, src/structure/expression.rs, src/structure/for_expr.rs, src/structure/mod.rs, src/structure/ser/tests.rs, src/structure/template_expr.rs, src/structure/tests.rs
Also marks `hcl::structure::Identifier` as deprecated. This symbol will be removed in a future release.
For most users this shouldn't be an issue since the `Identifier` type was always available as `hcl::Identifier` and none of the usage examples referenced to it as `hcl::structure::Identifier`.
Relates to #100
=> chore: move `Identifier` type to crate root

src/expr/mod.rs, src/format/impls.rs, src/format/mod.rs, src/value/mod.rs
Identifiers are validated upon creation and are always valid if created via `Identifier::new` or `Identifier::sanitized`. The formatter does not need to validate them again. This also obsoletes the internal strict mode and `to_string_unchecked` function.
Invalid identifiers can only be created via `Identifier::unchecked`, but this would be a user error as stated in the method docs.
=> chore(format): remove ident validation

README.md, src/eval/mod.rs, src/lib.rs, src/macros.rs, src/number.rs, src/template.rs
Hide some exports at the crate root from the docs. It got pretty crowded in there and it's really hard to see which types are the most relevant. Re-exporting every single type from the `expr` and `structure` module was a mistake. Only the most useful ones should be re-exported.
Furthermore the `block_label!` and `object_key!` macros are hidden now as well since they do not add much value on their own. They're more meant for internal usage to build higher level macros like `block!` and `expression!`.
This is not a breaking change. The exports are still usable but hidden from the docs with the intention to remove them entirely in a future release.
=> fix: unclutter crate root exports

src/lib.rs, src/value/mod.rs, src/value/ser.rs
This allows to convert arbitrary types implementing `Serialize` into a `Value`. It will be used by the `value!` macro that will be added in a separate change.
=> feat(value): add `ValueSerializer` and `to_value`

src/de/mod.rs, src/de/tests.rs, src/macros.rs, src/ser/tests.rs, src/structure/tests.rs
This can be used in places where `serde_json::json!` was used previously. It has the same syntax as the `expression!` macro with some restrictions around raw expressions.
=> feat(macros): add `value!` macro

src/format/mod.rs, src/format/tests.rs
The `Formatter` can be configured to emit more compact arrays and objects via the newly added builder methods `compact`, `compact_arrays` and `compact_objects`.
=> feat(format): add support for compact collection formatting

README.md, src/eval/expr.rs, src/eval/impls.rs, src/eval/mod.rs, src/eval/tests.rs
BREAKING CHANGE: the `Evaluate` implementation of `TemplateExpr` returns a `Value` instead of a `String` now to support interpolation unwrapping.
This implements template interpolation unwrapping as described in https://github.com/hashicorp/hcl/blob/main/hclsyntax/spec.md#template-interpolation-unwrapping
It also fixes a bug in the object key evaluation logic. See the comment on `evaluate_object_key` (renamed from `evaluate_string`).
=> fix!(eval): correctly handle interpolation unwrapping

src/parser/expr.rs, src/parser/grammar/hcl.pest, src/parser/tests.rs
Previously, heredocs could contain invalid HCL templates. Now these will fail to parse.
=> fix(parser): improve grammar for heredoc

src/format/impls.rs, src/format/mod.rs, src/format/tests.rs, src/parser/expr.rs, src/util.rs
=> fix(format): prevent double-escaping of template strings

src/format/impls.rs, src/format/mod.rs, src/format/tests.rs, src/ident.rs, src/lib.rs, src/util.rs
This allows to configure the formatting behaviour for object key strings that are valid HCL identifiers as well. This is not enabled by default.
Closes #132
=> feat(format): add `prefer_ident_keys` to `FormatterBuilder`

Cargo.toml
Since dependabot does not do this in absence of a `Cargo.lock`, we need to do it manually.
=> chore(deps): bump dependencies to latest versions

src/format/mod.rs, src/format/tests.rs, src/ser/mod.rs
This makes using a custom `Formatter` more convenient. The new `build_vec` method of `FormatterBuilder` returns a `Formatter` with an internal `Vec<u8>` buffer which can be used in combination with `Format::format_string` and `Format::format_vec`.
The `Serializer` also received the `serialize_string` and `serialize_vec` methods for writers implementing `AsMut<Vec<u8>>`.
This change also lowers the number of unsafe usages in this crate from 3 to 1.
=> feat(format): allow formatting to `String` and `Vec<u8>` directly

src/eval/template.rs, tests/eval.rs
This fixes two issues:
- Whitespace should only be stripped from literals up until (and including) the next line break. Previously, all preceding/following line breaks were removed.
- The `for` directive's strip mode must be applied to all templates that are looped over, not just the first and last collection item.
=> fix(eval): implement correct template literal stripping

Cargo.toml, README.md, src/expr/variable.rs, src/ident.rs, src/internal_string.rs, src/lib.rs
BREAKING CHANGE: The trait bounds on `Identifier::{new,unchecked}` and `Variable::{new,unchecked}` were changed from `Into<String>` to `Into<InternalString>`. This has no impact on common use cases involving std types but may break code using custom types.
Most identifiers are relatively short and can be inlined on the stack.
The `perf` feature improves parser performance by around 5%.
I could have added this to `Identifier` directly instead of creating a separate type. However, internal strings will be used in the new parser implementation to make tracking whitespace and comments in HCL documents more performant, so I'm already designing this as a reusable type not limited to identifiers.
=> feat(perf)!: optionally inline identifier strings on the stack

crates/hcl-rs/src/expr/template_expr.rs, crates/specsuite/tests/expressions/heredoc-noescape.hcl, crates/specsuite/tests/expressions/heredoc-noescape.t
[Current logic](https://github.com/martinohmann/hcl-rs/blob/5cf6f967adc18388b9c2d149d515ee603509bc36/crates/hcl-rs/src/expr/template_expr.rs#L52) has `TemplateExpr` doing a `try_unescape` with both a `QuotedString` and `Heredoc` inside  `fmt::Display` This causes side effects when legitimate and valid \\ characters are contained within a heredoc
This shows itself with bash scripts, or regular expressions which need escaping. The use case which stumbled upon this was regex in TOML.
```
let content = r###"
config = {
content = <<-EOT
www\\.example\\.com
EOT
}
"###;
println!("{}", hcl::to_string(hcl::from_str(&content)?)?);
```
The output `content` is the string `www\.example\.com` which is incorrect, this PR corrects that.   
As a side note, use of `hcl::eval::from_str` does not exhibit …
=> fix(format): Do not unescape heredoc strings

crates/hcl-edit/src/parser/expr.rs, crates/hcl-edit/src/parser/tests.rs
=> fix(parser): handle `/` ambiguity in expression parser

crates/hcl-edit/README.md, crates/hcl-edit/src/expr/mod.rs, crates/hcl-edit/src/lib.rs, crates/hcl-edit/src/structure/mod.rs, crates/hcl-edit/src/visit.rs, crates/hcl-edit/src/visit_mut.rs
This uses the same design as the `syn` and `toml_edit` crates.
=> feat: add `visit` and `visit_mut` modules

crates/hcl-edit/src/expr/array.rs, crates/hcl-edit/src/expr/func_call.rs, crates/hcl-edit/src/expr/object.rs, crates/hcl-edit/src/parser/expr.rs, crates/hcl-edit/src/structure/mod.rs, crates/hcl-edit/src/template/mod.rs
BREAKING CHANGE: `FuncArgs::new` does not take any arguments anymore to align with constructors of other collection types. Use `FuncArgs::from(args)`, `FuncArgs::from_iter(args)` and `FuncArgs::push(arg)` instead.
=> feat!: add useful collection methods

crates/hcl-edit/src/structure/mod.rs, crates/hcl-edit/src/visit_mut.rs, crates/hcl-primitives/src/ident.rs, crates/hcl-rs/src/ident.rs
In a followup change `Ident::new` will be changed panic when provided with an invalid identifier. The return type will be changed from `Result<Ident, Error>` to `Ident`.
=> feat(ident): add `Ident::try_new`

crates/hcl-primitives/src/ident.rs
BREAKING CHANGE: `Ident::new` now returns `Ident` instead of `Result<Ident, Error>` and will panic if an invalid identifier is encountered. Use `Ident::try_new` instead to get the old behaviour.
=> fix(ident)!: make `Ident::new` panic on invalid identifier

crates/hcl-edit/src/template/mod.rs
This avoids code duplication just for the sake of supporting a template variant that allows decoration.
=> fix(template): dereference `StringTemplate` to `Template`

crates/hcl-edit/src/template/mod.rs
This reverts commit 906b3a0ef7ae9299ebda820e0570788688ea9814.
=> revert(template): dereference `StringTemplate` to `Template`

crates/hcl-edit/src/encode/structure.rs, crates/hcl-edit/src/parser/structure.rs, crates/hcl-edit/src/structure/mod.rs, crates/hcl-edit/src/visit.rs, crates/hcl-edit/src/visit_mut.rs
BREAKING CHANGE: The `BlockBody` and `OnelineBody` types were removed. `Block` now directly uses `Body`. One-line blocks can still be constructed by calling `body.set_prefer_oneline(true)`.
This removes some unnecessary layer of abstraction which made working with blocks more complicated than it needed to be.
=> refactor(structure)!: remove `BlockBody` and `OnelineBody`

crates/hcl-edit/src/parser/structure.rs, crates/hcl-edit/src/structure/mod.rs
BREAKING CHANGE: `Block::new` now only accepts a single `ident` argument. Set the block body, by updating `body` field of `Block`.
=> refactor!(structure): remove `body` argument from `Block::new`

crates/hcl-edit/Cargo.toml, crates/hcl-edit/src/parser/expr.rs, crates/hcl-edit/src/parser/number.rs, crates/hcl-edit/src/parser/string.rs, crates/hcl-edit/src/parser/structure.rs, crates/hcl-edit/src/parser/template.rs, crates/hcl-edit/src/parser/trivia.rs
This change also migrates a number of deprecated items to their recommended replacements.
=> chore(deps): bump winnow to 0.4.6

crates/hcl-edit/src/parser/state.rs, crates/hcl-edit/src/structure/attribute.rs, crates/hcl-edit/src/structure/body.rs, crates/hcl-edit/src/structure/mod.rs, crates/hcl-edit/src/visit_mut.rs
BREAKING CHANGE: Various `Body` methods were changed to return `AttributeMut<'a>`/`StructureMut<'a>` instead of `&'a mut Attribute`/`&'a mut Structure` to prevent mutable access to attribute keys. The `VisitMut` trait was updated to reflect these changes as well.
A HCL body must not contain duplicate attribute keys. Multiple instances of the same block identifier are allowed, though. This change updates the `Body` type to make it impossible to insert a given attribute key twice, or to obtain a mutable reference to one.
=> feat(structure)!: prevent duplicate attribute keys in `Body`

crates/hcl-edit/src/encode/mod.rs, crates/hcl-edit/src/expr/array.rs, crates/hcl-edit/src/expr/conditional.rs, crates/hcl-edit/src/expr/for_expr.rs, crates/hcl-edit/src/expr/func_call.rs, crates/hcl-edit/src/expr/mod.rs, crates/hcl-edit/src/expr/object.rs, crates/hcl-edit/src/expr/operation.rs, crates/hcl-edit/src/expr/traversal.rs, crates/hcl-edit/src/lib.rs, crates/hcl-edit/src/macros.rs, crates/hcl-edit/src/parser/expr.rs, crates/hcl-edit/src/parser/repr.rs, crates/hcl-edit/src/parser/state.rs, crates/hcl-edit/src/parser/string.rs, crates/hcl-edit/src/parser/structure.rs, crates/hcl-edit/src/parser/template.rs, crates/hcl-edit/src/parser/tests.rs, crates/hcl-edit/src/structure/attribute.rs, crates/hcl-edit/src/structure/block.rs, crates/hcl-edit/src/structure/body.rs, crates/hcl-edit/src/structure/mod.rs, crates/hcl-edit/src/template/mod.rs, crates/hcl-edit/src/visit.rs, crates/hcl-edit/src/visit_mut.rs
This makes them easier to discover since they are a core feature of `hcl-edit`. At the same time the `repr` module is hidden from the docs and will eventually be made private in a future change.
=> feat(repr): re-export types from crate root

crates/hcl-primitives/src/template.rs
This adds functions to escape/unescape interpolation sequence and directive control flow start markers.
These are a prerequisite to properly fix https://github.com/martinohmann/hcl-rs/issues/242.
=> feat(template): add `{escape,unescape}_markers`

crates/hcl-edit/src/encode/template.rs, crates/hcl-edit/src/parser/string.rs, crates/hcl-edit/src/parser/template.rs, crates/hcl-edit/src/parser/tests.rs, crates/hcl-rs/src/eval/mod.rs, crates/hcl-rs/src/format/impls.rs, crates/hcl-rs/src/parser/template.rs, crates/hcl-rs/tests/regressions.rs
Fixes #242
Closes #243
This fixes the handling of `${` and `%{` markers in template literals.
When a HCL template literal contains escaped interpolation sequence or directive control flow start markers (`$${` and `%%{` respectively), they will be automatically unescaped while parsing now.
Additionally, formatting a `Element::Literal` containing `${` or `%{` as HCL will now correctly emit `$${` and `%%{`.
=> fix(template): properly handle escaping of interpolation/directive markers

crates/hcl-edit/src/encode/mod.rs, crates/hcl-edit/src/parser/string.rs, crates/hcl-edit/tests/regressions.rs, crates/hcl-rs/src/format/impls.rs, crates/hcl-rs/src/format/mod.rs, crates/hcl-rs/src/parser/mod.rs, crates/hcl-rs/tests/regressions.rs
Closes https://github.com/martinohmann/hcl-rs/issues/248
This is the same fix as made in https://github.com/martinohmann/hcl-rs/pull/247 for template literals, just for
strings.
=> fix(string): properly handle escaping of interpolation/directive marker

crates/hcl-edit/src/parser/string.rs, crates/hcl-edit/src/parser/tests.rs, crates/hcl-edit/tests/regressions.rs
=> fix(parser): correctly handle escaped markers in templates

crates/hcl-edit/examples/interpolation-unwrapping.rs, crates/hcl-edit/src/template/mod.rs
This avoids the need to maintain duplicate methods just because of the additional decor that `StringTemplate` has over `Template`. It also enables some other improvements going forward.
=> refactor(template)!: make `StringTemplate` deref to `Template`

crates/hcl-rs/src/eval/error.rs, crates/hcl-rs/src/eval/impls.rs, crates/hcl-rs/src/expr/mod.rs, crates/hcl-rs/src/expr/ser/tests.rs, crates/hcl-rs/src/format/impls.rs, crates/hcl-rs/src/lib.rs, crates/hcl-rs/src/macros.rs, crates/hcl-rs/src/structure/tests.rs, crates/hcl-rs/src/tests.rs, crates/hcl-rs/tests/ser.rs
The construct was a mistake from the start and makes it possible to produce invalid HCL. It's also not needed anymore since all types from the HCL expression language are implemented.
=> fix(expr): deprecate `RawExpression`

crates/hcl-rs/Cargo.toml, crates/hcl-rs/examples/in-place-expr-evaluation.rs, crates/hcl-rs/src/eval/error.rs, crates/hcl-rs/src/eval/impls.rs, crates/hcl-rs/src/eval/mod.rs, crates/hcl-rs/tests/eval.rs
Closes #184.
Key difference to the existing `Evaluate::evaluate` method:
- It mutably borrows the value and tries to evaluate all nested expressions in-place.
- It returns all errors that it encounters, not just the first one.
This allows for partial expression evaluation, e.g. to support use cases where a HCL document contains variable references to other parts within the same document that themselves contain expressions that are not evaluated yet.
In this case one would:
1. Partially evaluate the document via `evaluate_in_place`.
2. Update the `Context` with newly discovered variables.
3. Repeat 1. and 2. until there are no more errors left.
=> feat(eval): add `Evaluate::evaluate_in_place`

crates/hcl-edit/src/parser/structure.rs, crates/hcl-edit/tests/regressions.rs
=> fix(parser): attach missing span information to identifiers

README.md
Closes https://github.com/martinohmann/hcl-rs/issues/304
=> docs: add section about feature parity with go-hcl

crates/hcl-edit/src/parser/error.rs
hcl-edit parser error already returns line and location, but message is also required for the user to be able to pretty print the error themselves
=> expose hcl-edit parser error message

crates/hcl-edit/src/encode/expr.rs, crates/hcl-edit/src/expr/func_call.rs, crates/hcl-edit/src/expr/mod.rs, crates/hcl-edit/src/parser/expr.rs, crates/hcl-edit/src/parser/tests.rs, crates/hcl-edit/src/visit.rs, crates/hcl-edit/src/visit_mut.rs, crates/hcl-edit/tests/parse.rs, crates/hcl-rs/src/eval/error.rs, crates/hcl-rs/src/eval/mod.rs, crates/hcl-rs/src/expr/de.rs, crates/hcl-rs/src/expr/edit.rs, crates/hcl-rs/src/expr/func_call.rs, crates/hcl-rs/src/expr/mod.rs, crates/hcl-rs/src/format/impls.rs, crates/hcl-rs/tests/format.rs
Closes https://github.com/martinohmann/hcl-rs/issues/335
This adds support for namespaced HCL function calls. The PR includes updates to the HCL parser (`hcl-edit`), formatter (`hcl-rs`), evaluation context (`hcl-rs`), encoder (`hcl-edit`) and visitors (`hcl-edit`).
BREAKING CHANGE: The `ident` field of `hcl_edit::expr::FuncCall` was renamed to `name`. Its type changed from `Decorated<Ident>` to `FuncName`. The type of `hcl::expr::FuncCall`'s `name` field changed from `Identifier` to `FuncName`. Various other places in the codebase that previously used bare identifiers as type now use `FuncName` to accommodate the change.
=> feat!: add support for namespaced functions

crates/hcl-rs/src/lib.rs, crates/hcl-rs/src/value/mod.rs
Add the `from_value` function to the `value` module, allowing users to convert a `Value` into a type `T` that implements `serde::de::Deserialize`.
Providing a convenient way to deserialize HCL `Value` into Rust types.
close #345
=> feat: add `from_value` function for deserializing HCL `Value`.

crates/hcl-rs/src/eval/error.rs, crates/hcl-rs/src/eval/impls.rs, crates/hcl-rs/src/expr/de.rs, crates/hcl-rs/src/expr/edit.rs, crates/hcl-rs/src/expr/mod.rs, crates/hcl-rs/src/expr/ser/mod.rs, crates/hcl-rs/src/format/impls.rs, crates/hcl-rs/src/lib.rs, crates/hcl-rs/src/macros.rs, crates/hcl-rs/src/template/mod.rs
BREAKING CHANGE: The deprecated `hcl::expr::RawExpression` type and the `hcl::template::StripMode` alias were removed. Instead of the latter use `hcl::template::Strip` instead. The former has not replacement.
=> fix!: remove deprecated items

crates/hcl-rs/src/de/mod.rs
This exposes a method to create an HCL `Deserializer` directly from a `Body`. I know the [from_body global fn](https://docs.rs/hcl-rs/latest/hcl/fn.from_body.html) already exists, but I specifically need a `Deserializer` so I can pass it to [serde_path_to_error::deserialize](https://docs.rs/serde_path_to_error/latest/serde_path_to_error/fn.deserialize.html).
I know `Body` already implements `IntoDeserializer`, but that creates a `NewtypeStructDeserializer<Vec<Structure>>` which doesn't seem to work for deserializing to arbitrary `Deserialize` types.
I didn't add any tests to this because it's so trivial. Happy to write one though if you'd prefer to have it.
=> feat: Add from_body to Deserializer

crates/hcl-edit/src/parser/expr.rs, crates/hcl-edit/src/parser/string.rs, crates/hcl-edit/src/parser/template.rs, crates/hcl-edit/tests/regressions.rs
Fixes #426.
I also found another case where multiline expressions are valid but the parser didn't handle so far and fixed that along the way.
Also contains some `rustfmt` changes.
=> fix(parser): allow multiline expressions in more places

crates/hcl2json/src/main.rs
There are two kinds of empty collections to emit when paths are empty:
- `[]` if `--file-paths/-P` **is not**  provided
- `{}` if `--file-paths/-P` **is** provided
The current logic didn't account for that and even got it wrong for the default case, which should emit `[]`.
We'll just remove this fast path since it does not bring any performance benefit (`bulk_convert` is only called exactly once) but needs to be kept in sync with the rest of the logic.
=> fix: emit correct empty collection if paths are empty

crates/hcl-edit/src/parser/template.rs, crates/hcl-edit/src/template/mod.rs, crates/hcl-rs/src/eval/impls.rs, crates/hcl-rs/src/template/edit.rs, crates/hcl-rs/src/template/mod.rs
When Rust allocates memory for enum variants, the compiler allocates memory equal to the maximum size among all variants. This becomes inefficient when there's a significant size difference between the largest and smallest variants. In our case, the Element enum had variants with sizes ranging from small literals to large directive structures (480+ bytes).
By wrapping each variant with Box, we allocate only the memory of a smart pointer (8 bytes on 64-bit systems) on the stack, while the actual data is stored on the heap. This optimization reduces the enum's stack footprint and improves cache locality for frequently accessed smaller variants.
- Wrapped `Element::Literal(Spanned<String>)` → `Element::Literal(Box<Spanned<String>>)`
- …
=> Performance improvements by boxing large enum variants

crates/hcl-edit/src/parser/error.rs, crates/hcl-edit/tests/regressions.rs
`hcl_edit::parser::parse_expr("")` panics when finding the span (subtracts from 0usize). I have tried to do a saturating_sub, but then it still fails later at `a..=b`, where b=0 and I didn't want to get into changing the semantics of b to change it to `a..b`.
=> fix: panic when parsing empty expression
